version: "3.7"

services:

  web:
    build: .
    image: web
    container_name: backend
    ports:
      - 8080:5000
    environment: 
      - REDIS_URL=redis://redis:6379
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis

  worker:
    image: web
    environment: 
      - REDIS_URL=redis://redis:6379
    command: rq worker --url redis://redis:6379 --with-scheduler
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis

  redis:
    image: redis:6